workflow 11

diff --git a/.github/workflows/api-state-tests.yml b/.github/workflows/api-state-tests.yml
--- a/.github/workflows/api-state-tests.yml
+++ b/.github/workflows/api-state-tests.yml
@@ -6,7 +6,7 @@ on:
       - '.github/workflows/api-state-tests.yml'
 jobs:
   test_bootstrap_1:
-    name: Bootstrap - MySQL and OIDC unavailable
+    name: Boot - without deps
     runs-on: ubuntu-latest
     steps:
       - name: Check out the repo
@@ -63,7 +63,7 @@ jobs:
             echo "State changed messages count is not $expected, it is $count"
             exit 1
           fi
-      - name: Check last message
+      - name: Check last log record
         working-directory: ./api/source
         run: |
           expected='"Application stopped"'
@@ -71,11 +71,11 @@ jobs:
           if [ "$last_message" == "$expected" ]; then
             echo "Last message is $expected"
           else
-            echo "Last message is not as expected, it is $last_message"
+            echo "Last message is not $expected, it is $last_message"
             exit 1
           fi
   test_bootstrap_2:
-    name: Bootstrap - MySQL available, OIDC unavailable
+    name: Boot - no OIDC
     runs-on: ubuntu-latest
     env:
       STIGMAN_DB_PASSWORD: stigman
@@ -155,7 +155,7 @@ jobs:
             echo "State changed messages count is not $expected, it is $count"
             exit 1
           fi
-      - name: Check last message
+      - name: Check last log record
         working-directory: ./api/source
         run: |
           expected='"Application stopped"'
@@ -163,11 +163,11 @@ jobs:
           if [ "$last_message" == "$expected" ]; then
             echo "Last message is $expected"
           else
-            echo "Last message is not as expected, it is $last_message"
+            echo "Last message is not $expected, it is $last_message"
             exit 1
           fi
   test_bootstrap_3:
-    name: Bootstrap - MySQL uavailable, OIDC available
+    name: Boot - no MySQL
     runs-on: ubuntu-latest
     env:
       STIGMAN_OIDC_PROVIDER: http://127.0.0.1:8080/auth/realms/stigman
@@ -231,7 +231,7 @@ jobs:
             echo "State changed messages count is not $expected, it is $count"
             exit 1
           fi
-      - name: Check last message
+      - name: Check last log record
         working-directory: ./api/source
         run: |
           expected='"Application stopped"'
@@ -239,8 +239,102 @@ jobs:
           if [ "$last_message" == "$expected" ]; then
             echo "Last message is $expected"
           else
-            echo "Last message is not as expected, it is $last_message"
+            echo "Last message is not $expected, it is $last_message"
             exit 1
           fi
-
+  test_bootstrap_4:
+    name: Boot - with deps
+    runs-on: ubuntu-latest
+    env:
+      STIGMAN_DB_PASSWORD: stigman
+      STIGMAN_OIDC_PROVIDER: http://127.0.0.1:8080/auth/realms/stigman
+    steps:
+      - name: Check out the repo
+        uses: actions/checkout@v4
+      - name: Run mock Keycloak
+        working-directory: ./test/api/mock-keycloak
+        run: |
+          python3 -m http.server 8080 &      
+      - name: Docker run MySQL
+        working-directory: ./api/source
+        run: |
+          docker run -d --name stig-manager-db \
+          -p 3306:3306 \
+          -e MYSQL_ROOT_PASSWORD=rootpw \
+          -e MYSQL_DATABASE=stigman \
+          -e MYSQL_USER=stigman \
+          -e MYSQL_PASSWORD=stigman \
+          mysql:8.0.24
+      - name: Wait for MySQL
+        working-directory: ./api/source
+        run: |
+          for i in {1..10}; do
+            echo "Waiting for MySQL to start"
+            if docker exec stig-manager-db mysql -ustigman -pstigman -e "SELECT 1" stigman &> /dev/null; then
+              echo "MySQL is up"
+              break
+            fi
+            sleep 1
+          done
+      - name: Install api libraries
+        working-directory: ./api/source
+        run: npm ci
+      - name: Run API
+        working-directory: ./api/source
+        run: |
+          set +e
+          timeout 30 node index.js | tee api-log.json
+          exit_code="${PIPESTATUS[0]}"
+          if [ $exit_code -eq 124 ]; then
+            echo "timeout timed out"
+            exit 0
+          else
+            echo "api exited before timeout"
+            exit 1
+          fi
+      - name: Check MySQL preflight failures
+        working-directory: ./api/source
+        run: |
+          expected=0
+          count=$(jq -s 'map(select(.component == "mysql" and .type == "preflight" and .data.success == false)) | length' api-log.json)
+          if [ "$count" -eq $expected ]; then
+            echo "MySQL preflight failures count is $expected"
+          else
+            echo "MySQL preflight failures count is not $expected, it is $count"
+            exit 1
+          fi
+      - name: Check OIDC discovery failures
+        working-directory: ./api/source
+        run: |
+          expected=0
+          count=$(jq -s 'map(select(.component == "oidc" and .type == "discovery" and .data.success == false)) | length' api-log.json)
+          if [ "$count" -eq $expected ]; then
+            echo "OIDC discovery failures count is $expected"
+          else
+            echo "OIDC discovery failures count is not $expected, it is $count"
+            exit 1
+          fi
+      - name: Check statechanged messages
+        working-directory: ./api/source
+        run: |
+          expected=1
+          count=$(jq -s 'map(select(.type == "statechanged" and .data.currentState == "operational" and .data.previousState == "starting"))|length' api-log.json)
+          if [ "$count" -eq $expected ]; then
+            echo "State changed messages count is $expected"
+          else
+            echo "State changed messages count is not $expected, it is $count"
+            exit 1
+          fi
+      - name: Check last log record
+        working-directory: ./api/source
+        run: |
+          expected='"started"'
+          last_message=$(jq -s '.[-1].type' api-log.json)
+          if [ "$last_message" == "$expected" ]; then
+            echo "Last type is $expected"
+          else
+            echo "Last type is not $expected, it is $last_message"
+            exit 1
+          fi
+  
         
